name = "playdota2win"
main = "src/worker.js"
compatibility_date = "2026-01-15"

[vars]
TURNSTILE_ENABLED = "true"

[[kv_namespaces]]
binding = "APP_KV"
id = "f2e0a96f51484204b4a3253bd4d17772"

[[r2_buckets]]
binding = "UPLOADS_BUCKET"
bucket_name = "downloads"

[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

[observability]
[observability.logs]
enabled = false
invocation_logs = true
